### ISSUE TITLE
Agentforce is not working in VS code 

### ISSUE THREAD

**Issue by lokeshsinghbunny** [forcedotcom/Einstein-GPT-for-Developers#108]
Agentforce is not working in VS code. Receiving below error message on execting any prompt

error message: 

queryLlmWithFileContent ~ error: {message: "Sorry I couldn't connect to the backend.", stack: "ChatServiceError: Sorry I couldn't connect to the …rcedx-einstein-gpt-1.3.0\\dist\\index.js:241:16683)", name: 'ChatServiceError'}message: "Sorry I couldn't connect to the backend."name: "ChatServiceError"stack: "ChatServiceError: Sorry I couldn't connect to the backend.\n    at z4.getChatStream (c:\\Users\\lb9188\\.vscode\\extensions\\salesforce.salesforcedx-einstein-gpt-1.3.0\\dist\\index.js:259:827)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at bu.handleWebviewMessage (c:\\Users\\lb9188\\.vscode\\extensions\\salesforce.salesforcedx-einstein-gpt-1.3.0\\dist\\index.js:241:21222)\n    at mh.value (c:\\Users\\lb9188\\.vscode\\extensions\\salesforce.salesforcedx-einstein-gpt-1.3.0\\dist\\index.js:241:16683)"[[Prototype]]: Objectconstructor: ƒ Object()hasOwnProperty: ƒ hasOwnProperty()isPrototypeOf: ƒ isPrototypeOf()propertyIsEnumerable: ƒ propertyIsEnumerable()toLocaleString: ƒ toLocaleString()toString: ƒ toString()valueOf: ƒ valueOf()__defineGetter__: ƒ __defineGetter__()__defineSetter__: ƒ __defineSetter__()__lookupGetter__: ƒ __lookupGetter__()__lookupSetter__: ƒ __lookupSetter__()__proto__: (...)get __proto__: ƒ __proto__()set __proto__: ƒ __proto__()

Screenshort:
<img width="952" alt="image (1)" src="https://github.com/user-attachments/assets/a2b74890-f840-4db7-ab3a-f29d02be23a4">
<img width="203" alt="image" src="https://github.com/user-attachments/assets/c5cc439d-a7ee-45a3-8dd7-002af5c60fe7">

**Comment by jonifazo** [comment]
Hi [lokeshsinghbunny](https://github.com/lokeshsinghbunny) - Have you tried re-authenticating to your org? 
If that doesn't help, do you see any additional errors in the Developer Tools, or under Output > Einstein for Developers?

**Comment by akkibaddiex** [comment]
console.ts:137 [Extension Host] DefaultOrg ~ Error encountered getting a JWT from the DefaultOrg. InvalidJWTTokenError: We couldn’t access your Salesforce org. Try again, and if the issue persists, ask your admin for help.


Facing similar issue, checked that agent force is enabled in the sandbox, tried logging out and auth again. still seeing abve error.

**Comment by diyer** [comment]
Please create a new issue if you still encounter this.
