### ISSUE TITLE
AGENTFORCE : Dev Assistant not working on my vscode

### ISSUE THREAD

**Issue by oumaimazayate** [forcedotcom/Einstein-GPT-for-Developers#114]
### Summary

the agentforce for dev is not working on my vscode anymore.

### Expected result

when i try to explain some code or ask agentforce questions about salesforce apex, lwc i get this error 
"Oops, something went wrong. Try rewording your request or clearing the chat. If the problem persists, please let us know and we'll get it sorted out for you."
it's been like this for couple of weeks now, before that it used to work before and i used to get responses and explainations out of it. So i don't know what happened. 

I tried to uninstall it and reinstall it ==> still not working
I restarted the extensions ===> still not working

### Additional information

**Salesforce Extension Version in VS Code**: 62.5.1

**Salesforce Einstein For Developers Version in VS Code**: 1.5.0

**VS Code version**: 1.95.3
<img width="217" alt="error agentforce" src="https://github.com/user-attachments/assets/0d6f7f21-21a4-4198-88a4-e4fbdf22208f">

**Comment by klewis-sfdc** [comment]
Hi @oumaimazayate, Thank you for submitting the issue.  I'm sorry to hear that the Dev Assistant has not been working for you recently.

As a first step, can you confirm that Agentforce for Developers is enabled in the org you are connected to?  Go to Setup --> search "Agentforce for Developers".   A screenshot of that setup page in the org could be helpful.  Thank you!

**Comment by oumaimazayate** [comment]
I checked my org and the agentforce is enabled, here is the screenshot of the setup as demanded 
<img width="784" alt="enabled agent" src="https://github.com/user-attachments/assets/3cc32304-be89-4a21-81a0-f9510adb8738">

**Comment by klewis-sfdc** [comment]
Ok, thank you.  If you click on the A4D extension icon in the lower right corner of the IDE, what does the first line of the Status Menu display?
<img width="732" alt="2024-12-11_15-04-15" src="https://github.com/user-attachments/assets/88eb0c37-62e2-43c6-ae77-5a350fd6f690" />


If you open up the developer console (_Debug: Focus on Debug Console View_) and reload the window, do you see any error messages in the console log?  
<img width="738" alt="2024-12-11_15-05-48" src="https://github.com/user-attachments/assets/bd1fd5a1-3276-4570-875b-8e630eba5352" />



Screenshots of both of these areas would be helpful.

**Comment by gwpark** [comment]
My issue is the same as the above content. Below is the error content
  . Salesforce Extension Pack in Code Builder: 62.9.1
  . Salesforce Einstein For Developers Version in VS Code: 1.5.0
  . VS Code version: 1.95.3

[Below]
console.ts:137 [Extension Host] sfApiClient.getSfApiUrl {sfApiSettingEnv: 'Production', sfApiUrl: 'https://api.salesforce.com/einstein/gpt/code/v1-alpha.1/'}
console.ts:137 [Extension Host] DefaultOrg ~ Using cached JWT. {currentJwt: {…}}
console.ts:137 [Extension Host] sfApiClient.getSfApiRegion {sfApiSettingEnv: 'Production', sfApiRegion: 'us-east-1'}
console.ts:137 [Extension Host] Tracing header sfapi /embeddings {x-client-trace-id: 'eGPT-trace_de7d2fcc-86cc-47ad-a7a5-c0615a78abd3_3cd4351d-555c-48e3-acb7-8715321c59b1'}
console.ts:137 [Extension Host] In AxiosClient, axiosClient.handleError AxiosError: Request failed with status code 500
console.ts:137 [Extension Host] Error creating embeddings {error: {…}}
log.ts:439   ERR [Extension Host] Error encountered requesting chat stream:  Error: Error while validating prompt: Error: Failed to create embedding for prompt
	at t.isOnTopic (c:\Users\dsgp15194.id\.vscode\extensions\salesforce.salesforcedx-einstein-gpt-1.5.0\dist\index.js:293:280)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async t.validatePrompt (c:\Users\dsgp15194.id\.vscode\extensions\salesforce.salesforcedx-einstein-gpt-1.5.0\dist\index.js:291:6840)
	at async $4.validateChatPrompt (c:\Users\dsgp15194.id\.vscode\extensions\salesforce.salesforcedx-einstein-gpt-1.5.0\dist\index.js:298:150)
	at async $4.buildChatRequestBody (c:\Users\dsgp15194.id\.vscode\extensions\salesforce.salesforcedx-einstein-gpt-1.5.0\dist\index.js:297:1146)
	at async $4.getChatStream (c:\Users\dsgp15194.id\.vscode\extensions\salesforce.salesforcedx-einstein-gpt-1.5.0\dist\index.js:297:417)
	at async Eu.handleWebviewMessage (c:\Users\dsgp15194.id\.vscode\extensions\salesforce.salesforcedx-einstein-gpt-1.5.0\dist\index.js:275:20812)
	at async mh.value (c:\Users\dsgp15194.id\.vscode\extensions\salesforce.salesforcedx-einstein-gpt-1.5.0\dist\index.js:275:16233)
console.ts:137 [Extension Host] Error encountered requesting chat stream:  Error: Error while validating prompt: Error: Failed to create embedding for prompt
	at t.isOnTopic (c:\Users\dsgp15194.id\.vscode\extensions\salesforce.salesforcedx-einstein-gpt-1.5.0\dist\index.js:293:280)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async t.validatePrompt (c:\Users\dsgp15194.id\.vscode\extensions\salesforce.salesforcedx-einstein-gpt-1.5.0\dist\index.js:291:6840)
	at async $4.validateChatPrompt (c:\Users\dsgp15194.id\.vscode\extensions\salesforce.salesforcedx-einstein-gpt-1.5.0\dist\index.js:298:150)
	at async $4.buildChatRequestBody (c:\Users\dsgp15194.id\.vscode\extensions\salesforce.salesforcedx-einstein-gpt-1.5.0\dist\index.js:297:1146)
	at async $4.getChatStream (c:\Users\dsgp15194.id\.vscode\extensions\salesforce.salesforcedx-einstein-gpt-1.5.0\dist\index.js:297:417)
	at async Eu.handleWebviewMessage (c:\Users\dsgp15194.id\.vscode\extensions\salesforce.salesforcedx-einstein-gpt-1.5.0\dist\index.js:275:20812)
	at async mh.value (c:\Users\dsgp15194.id\.vscode\extensions\salesforce.salesforcedx-einstein-gpt-1.5.0\dist\index.js:275:16233)
uGi @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
S @ rpcProtocol.ts:458
Q @ rpcProtocol.ts:443
M @ rpcProtocol.ts:373
L @ rpcProtocol.ts:299
(anonymous) @ rpcProtocol.ts:161
B @ event.ts:1243
fire @ event.ts:1274
fire @ ipc.net.ts:652
l.onmessage @ localProcessExtensionHost.ts:378
VM7:2270 An error happened Error: Sorry I couldn't connect to the backend.
    at Aq (<anonymous>:697:5599)
    at async nq (<anonymous>:697:5652)
    at async Be (<anonymous>:2270:11618)
    at async m (<anonymous>:2270:4460)
VM7:686 sendTelemetry {"commandName":"sfdx__eGPT_chat_interaction_event","commandSource":"Chat","promptId":"3cd4351d-555c-48e3-acb7-8715321c59b1","sequenceId":"","codeBlockQuantity":0,"status":"failed","sessionId":"ed8b8e32-97f9-4cfd-b87b-c5db291932ad","questionLength":"84"}

**Comment by diyer** [comment]
closing this as Dev assistant is deprecated
